spring.datasource.url=jdbc:postgresql://localhost:5432/lab9demo
spring.datasource.username=postgres
spring.datasource.password=Fayq592

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081